In [52]:
import pandas as pd
import numpy as np

In [53]:
import os 
dir = r"C:\Users\HP\Downloads\proj\dataset\train\boxes_transcripts_labels"
list_items = os.listdir(dir)
# list_items

In [54]:
tsv_files=[]
for item in list_items:
    if item.endswith('.tsv'):
        full_path = os.path.join(dir,item)
        tsv_files.append(full_path)

# print(tsv_files)
dataframes =[]
for file in tsv_files:
    df = pd.read_csv(file ,header =None, delimiter =',')
    selected_columns = df.iloc[: , [0,1,2,3,4,5,7]]
    dataframes.append(selected_columns)

combined_data = pd.concat(dataframes, ignore_index=True)

# Rename columns for clarity
combined_data.columns = ['start_index' ,'end_index' ,'top_left_x', 'top_left_y', 'bottom_right_x', 'bottom_right_y', 'label_text' ]

combined_data

,start_index,end_index,top_left_x,top_left_y,bottom_right_x,bottom_right_y,label_text
0,33,33,215,4,227,21,OTHER
1,35,44,235,3,308,21,OTHER
2,46,51,311,3,349,20,OTHER
3,53,60,352,3,401,20,OTHER
4,62,67,404,3,457,21,OTHER
...,...,...,...,...,...,...,...
237611,2325,2327,365,1064,385,1079,OTHER
237612,2329,2334,388,1064,429,1079,OTHER
237613,2336,2338,451,1063,482,1078,OTHER
237614,2340,2342,485,1063,509,1078,OTHER
237615,2344,2352,511,1063,572,1078,OTHER

In [55]:
combined_data['label_text'].unique()

array(['OTHER', 'ssnOfEmployee', 'einEmployerIdentificationNumber',
       'box1WagesTipsAndOtherCompensations',
       'box2FederalIncomeTaxWithheld', 'employerName',
       'box3SocialSecurityWages', 'box4SocialSecurityTaxWithheld',
       'employerAddressStreet_name', 'employerAddressZip',
       'employerAddressCity', 'employerAddressState', 'employeeName',
       'taxYear', 'box16StateWagesTips', 'box17StateIncomeTax'],
      dtype=object)

In [56]:
attributes = [
    'OTHER', 'ssnOfEmployee', 'einEmployerIdentificationNumber',
    'box1WagesTipsAndOtherCompensations', 'box2FederalIncomeTaxWithheld', 
    'employerName', 'box3SocialSecurityWages', 'box4SocialSecurityTaxWithheld',
    'employerAddressStreet_name', 'employerAddressZip',
    'employerAddressCity', 'employerAddressState', 'employeeName',
    'taxYear', 'box16StateWagesTips', 'box17StateIncomeTax'
]

# Create the dictionary mapping
attribute_mapping = {attribute: idx for idx, attribute in enumerate(attributes)}

print(attribute_mapping)

{'OTHER': 0, 'ssnOfEmployee': 1, 'einEmployerIdentificationNumber': 2, 'box1WagesTipsAndOtherCompensations': 3, 'box2FederalIncomeTaxWithheld': 4, 'employerName': 5, 'box3SocialSecurityWages': 6, 'box4SocialSecurityTaxWithheld': 7, 'employerAddressStreet_name': 8, 'employerAddressZip': 9, 'employerAddressCity': 10, 'employerAddressState': 11, 'employeeName': 12, 'taxYear': 13, 'box16StateWagesTips': 14, 'box17StateIncomeTax': 15}

In [57]:
combined_data['label_text'].replace(attribute_mapping , inplace=True)
combined_data

,start_index,end_index,top_left_x,top_left_y,bottom_right_x,bottom_right_y,label_text
0,33,33,215,4,227,21,0
1,35,44,235,3,308,21,0
2,46,51,311,3,349,20,0
3,53,60,352,3,401,20,0
4,62,67,404,3,457,21,0
...,...,...,...,...,...,...,...
237611,2325,2327,365,1064,385,1079,0
237612,2329,2334,388,1064,429,1079,0
237613,2336,2338,451,1063,482,1078,0
237614,2340,2342,485,1063,509,1078,0
237615,2344,2352,511,1063,572,1078,0

In [58]:
X= combined_data[['start_index' ,'end_index','top_left_x', 'top_left_y', 'bottom_right_x', 'bottom_right_y' ]].values

# Labels: Column 'class_label'
Y = combined_data['label_text'].values

In [68]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X, Y)

DecisionTreeClassifier()

In [72]:
from sklearn.model_selection import GridSearchCV

In [71]:
param_dist ={
    "criterion" :["gini","entropy"],
    "max_depth" :[1,2,3,4,5,6,7,8,None]
}

In [73]:
grid =GridSearchCV(clf ,param_grid =param_dist , cv =10 ,n_jobs =-1)

In [74]:
grid.fit(X,Y)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, None]})

In [78]:
grid.best_params_

{'criterion': 'entropy', 'max_depth': None}

In [77]:
best_model = grid.best_estimator_

### testing the model

In [62]:
import os

directory = r'C:\Users\HP\Downloads\proj\dataset\val_w_ann\boxes_transcripts_labels'
test_list_items = os.listdir(directory)
tsv_files=[]
for item in test_list_items:
    if item.endswith('.tsv'):
        full_path = os.path.join(directory,item)
        tsv_files.append(full_path)

# print(tsv_files)
dataframes =[]
for file in tsv_files:
    df = pd.read_csv(file ,header =None, delimiter =',')
    selected_columns = df.iloc[: , [0,1,2,3,4,5,7]]
    dataframes.append(selected_columns)

combined_data_test = pd.concat(dataframes, ignore_index=True)

# Rename columns for clarity
combined_data_test.columns = ['start_index' ,'end_index' ,'top_left_x', 'top_left_y', 'bottom_right_x', 'bottom_right_y', 'label_text' ]

combined_data_test

,start_index,end_index,top_left_x,top_left_y,bottom_right_x,bottom_right_y,label_text
0,33,33,216,22,225,36,OTHER
1,35,44,235,21,309,36,OTHER
2,46,51,311,20,350,35,OTHER
3,53,60,353,19,402,34,OTHER
4,62,67,405,19,456,33,OTHER
...,...,...,...,...,...,...,...
80448,2335,2337,364,1064,386,1078,OTHER
80449,2339,2344,389,1063,430,1078,OTHER
80450,2346,2348,451,1063,482,1077,OTHER
80451,2350,2352,484,1064,508,1077,OTHER
80452,2354,2362,510,1063,569,1077,OTHER

In [63]:
combined_data_test['label_text'].replace(attribute_mapping , inplace=True)
combined_data_test

,start_index,end_index,top_left_x,top_left_y,bottom_right_x,bottom_right_y,label_text
0,33,33,216,22,225,36,0
1,35,44,235,21,309,36,0
2,46,51,311,20,350,35,0
3,53,60,353,19,402,34,0
4,62,67,405,19,456,33,0
...,...,...,...,...,...,...,...
80448,2335,2337,364,1064,386,1078,0
80449,2339,2344,389,1063,430,1078,0
80450,2346,2348,451,1063,482,1077,0
80451,2350,2352,484,1064,508,1077,0
80452,2354,2362,510,1063,569,1077,0

In [64]:
Xtest= combined_data_test.iloc[: ,0:6].values
Ytest =combined_data_test.iloc[: ,6].values

In [65]:
Xtest

array([[  33,   33,  216,   22,  225,   36],
       [  35,   44,  235,   21,  309,   36],
       [  46,   51,  311,   20,  350,   35],
       ...,
       [2346, 2348,  451, 1063,  482, 1077],
       [2350, 2352,  484, 1064,  508, 1077],
       [2354, 2362,  510, 1063,  569, 1077]], dtype=int64)

In [79]:
test_predictions = best_model.predict(Xtest)

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(Ytest ,test_predictions)

0.9898947211415361